inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/setup

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - Rakefile
    - config/**/**.*
    - bin/spring
    - spec/rails_helper.rb
